//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CreditPlusEntities : DbContext
    {
        public CreditPlusEntities()
            : base("name=CreditPlusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Customer> Rabo_WWW_CustomerDetail(Nullable<decimal> customerId)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Customer>("Rabo_WWW_CustomerDetail", customerIdParameter);
        }
    
        public virtual int Rabo_WWW_DealDetails(Nullable<decimal> dealId)
        {
            var dealIdParameter = dealId.HasValue ?
                new ObjectParameter("DealId", dealId) :
                new ObjectParameter("DealId", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Rabo_WWW_DealDetails", dealIdParameter);
        }
    
        public virtual ObjectResult<Rabo_WWW_DealStructureDetails_Result> Rabo_WWW_DealStructureDetails(Nullable<decimal> dealStructureId)
        {
            var dealStructureIdParameter = dealStructureId.HasValue ?
                new ObjectParameter("DealStructureId", dealStructureId) :
                new ObjectParameter("DealStructureId", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rabo_WWW_DealStructureDetails_Result>("Rabo_WWW_DealStructureDetails", dealStructureIdParameter);
        }
    
        public virtual ObjectResult<Rabo_WWW_GetAddress_Result> Rabo_WWW_GetAddress(Nullable<decimal> clientId)
        {
            var clientIdParameter = clientId.HasValue ?
                new ObjectParameter("ClientId", clientId) :
                new ObjectParameter("ClientId", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rabo_WWW_GetAddress_Result>("Rabo_WWW_GetAddress", clientIdParameter);
        }
    
        public virtual ObjectResult<Rabo_WWW_GetAnswers_Result> Rabo_WWW_GetAnswers(Nullable<decimal> clientId)
        {
            var clientIdParameter = clientId.HasValue ?
                new ObjectParameter("ClientId", clientId) :
                new ObjectParameter("ClientId", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rabo_WWW_GetAnswers_Result>("Rabo_WWW_GetAnswers", clientIdParameter);
        }
    
        public virtual ObjectResult<Rabo_WWW_GetContacts_Result> Rabo_WWW_GetContacts(Nullable<decimal> clientId)
        {
            var clientIdParameter = clientId.HasValue ?
                new ObjectParameter("ClientId", clientId) :
                new ObjectParameter("ClientId", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rabo_WWW_GetContacts_Result>("Rabo_WWW_GetContacts", clientIdParameter);
        }
    
        public virtual int Rabo_WWW_GetCurrentRate(Nullable<decimal> clientId)
        {
            var clientIdParameter = clientId.HasValue ?
                new ObjectParameter("ClientId", clientId) :
                new ObjectParameter("ClientId", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Rabo_WWW_GetCurrentRate", clientIdParameter);
        }
    
        public virtual ObjectResult<Rabo_WWW_GetCustomerDeals_Result> Rabo_WWW_GetCustomerDeals(Nullable<decimal> customerId)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rabo_WWW_GetCustomerDeals_Result>("Rabo_WWW_GetCustomerDeals", customerIdParameter);
        }
    
        public virtual ObjectResult<Rabo_WWW_GetCustomers_Result> Rabo_WWW_GetCustomers(string searchString)
        {
            var searchStringParameter = searchString != null ?
                new ObjectParameter("SearchString", searchString) :
                new ObjectParameter("SearchString", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rabo_WWW_GetCustomers_Result>("Rabo_WWW_GetCustomers", searchStringParameter);
        }
    
        public virtual int Rabo_WWW_GetCustomersDeals(Nullable<decimal> customerId)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Rabo_WWW_GetCustomersDeals", customerIdParameter);
        }
    
        public virtual ObjectResult<Rabo_WWW_GetDates_Result> Rabo_WWW_GetDates(Nullable<decimal> clientId)
        {
            var clientIdParameter = clientId.HasValue ?
                new ObjectParameter("ClientId", clientId) :
                new ObjectParameter("ClientId", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rabo_WWW_GetDates_Result>("Rabo_WWW_GetDates", clientIdParameter);
        }
    
        public virtual ObjectResult<Rabo_WWW_GetDeals_Result> Rabo_WWW_GetDeals(string searchString)
        {
            var searchStringParameter = searchString != null ?
                new ObjectParameter("SearchString", searchString) :
                new ObjectParameter("SearchString", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rabo_WWW_GetDeals_Result>("Rabo_WWW_GetDeals", searchStringParameter);
        }
    
        public virtual ObjectResult<Rabo_WWW_GetDealStructures_Result> Rabo_WWW_GetDealStructures(string searchString)
        {
            var searchStringParameter = searchString != null ?
                new ObjectParameter("SearchString", searchString) :
                new ObjectParameter("SearchString", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rabo_WWW_GetDealStructures_Result>("Rabo_WWW_GetDealStructures", searchStringParameter);
        }
    
        public virtual ObjectResult<Rabo_WWW_GetDealStructuresDeals_Result> Rabo_WWW_GetDealStructuresDeals(Nullable<decimal> dealStructureId)
        {
            var dealStructureIdParameter = dealStructureId.HasValue ?
                new ObjectParameter("DealStructureId", dealStructureId) :
                new ObjectParameter("DealStructureId", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rabo_WWW_GetDealStructuresDeals_Result>("Rabo_WWW_GetDealStructuresDeals", dealStructureIdParameter);
        }
    
        public virtual ObjectResult<Rabo_WWW_GetDrawDownItems_Result> Rabo_WWW_GetDrawDownItems(Nullable<decimal> client)
        {
            var clientParameter = client.HasValue ?
                new ObjectParameter("Client", client) :
                new ObjectParameter("Client", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rabo_WWW_GetDrawDownItems_Result>("Rabo_WWW_GetDrawDownItems", clientParameter);
        }
    
        public virtual ObjectResult<Rabo_WWW_GetInstalments_Result> Rabo_WWW_GetInstalments(Nullable<decimal> clientId)
        {
            var clientIdParameter = clientId.HasValue ?
                new ObjectParameter("ClientId", clientId) :
                new ObjectParameter("ClientId", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rabo_WWW_GetInstalments_Result>("Rabo_WWW_GetInstalments", clientIdParameter);
        }
    
        public virtual ObjectResult<Rabo_WWW_GetLEvelData_Result> Rabo_WWW_GetLEvelData(Nullable<decimal> clientID)
        {
            var clientIDParameter = clientID.HasValue ?
                new ObjectParameter("ClientID", clientID) :
                new ObjectParameter("ClientID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rabo_WWW_GetLEvelData_Result>("Rabo_WWW_GetLEvelData", clientIDParameter);
        }
    
        public virtual ObjectResult<Rabo_WWW_GetPositions_Result> Rabo_WWW_GetPositions(Nullable<decimal> dealId)
        {
            var dealIdParameter = dealId.HasValue ?
                new ObjectParameter("DealId", dealId) :
                new ObjectParameter("DealId", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rabo_WWW_GetPositions_Result>("Rabo_WWW_GetPositions", dealIdParameter);
        }
    
        public virtual int Rabo_WWW_GetRateHistory(Nullable<decimal> clientId)
        {
            var clientIdParameter = clientId.HasValue ?
                new ObjectParameter("ClientId", clientId) :
                new ObjectParameter("ClientId", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Rabo_WWW_GetRateHistory", clientIdParameter);
        }
    
        public virtual int Rabo_WWW_GetTasks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Rabo_WWW_GetTasks");
        }
    }
}
